# Generated by Django 4.0.7 on 2022-10-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_customer_id_alter_featuredproducts_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
